### ISSUE TITLE
在VS2018和Creo8.0.0版本运行异步工程 显示“模块计算机类型“X86”与目标计算机类型“x64”冲突”

### ISSUE THREAD

**Issue by workversion** [slacker-HD/creo_toolkit#3]
# File Name
MAKEFILENAME = makefile

# Machine Type
PRO_MACHINE_TYPE = x86e_win64

# Executable names
EXE = AsyncProjectNOVS.exe

# Pro/Toolkit Source & Machine Loadpoint  (EXTERNAL USE - DEFAULT)
PROTOOL_SRC = ./src
# PROTOOL_SYS = "C:/PTC/Creo 2.0/Common Files/M060/protoolkit/x86e_win64"
# PROTOOL_HEAD = "C:/PTC/Creo 2.0/Common Files/M060/protoolkit/includes"

# Include File Paths
INCS = -I. -I"E:/protoolkit/includes" -I$(PROTOOL_SRC)/includes

# Compiler Flags
CC = cl
MACH = -DPRO_MACHINE=36 -DPRO_OS=4
CCFLAGS = /wd4430  /TP -c -GS -fp:precise -D_WSTDIO_DEFINED -DPRO_USE_VAR_ARGS -DPRO_USE_VAR_ARG  /Od /Z7
CFLAGS = $(CCFLAGS) $(INCS) $(MACH)

# Libraries
PTCLIBS = "E:/protoolkit/x86e_win64/obj/protoolkit_NU.lib" "E:/protoolkit/x86e_win64/obj/pt_asynchronous.lib"
LIBS = kernel32.lib user32.lib wsock32.lib advapi32.lib mpr.lib winspool.lib netapi32.lib psapi.lib gdi32.lib shell32.lib comdlg32.lib ole32.lib ws2_32.lib

# Object files
OBJS = Test.obj 

# Linker
LINK = "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/link.exe"

$(EXE) :  $(OBJS) $(PTCLIBS)
#Executable applications compiled using WinMain() instead of main() should set the subsystem to windows instead of console.
	$(LINK) /subsystem:console -out:$(EXE) /debug /debugtype:cv /machine:amd64 @<<longline.list 
$(OBJS) $(PTCLIBS) $(LIBS)
<<

# object dependencies
Test.obj:  $(PROTOOL_SRC)/Test.c
	$(CC) $(CFLAGS) $(PROTOOL_SRC)/Test.c

clean :
	del $(OBJS)
	del $(EXE)
	del $(MAKEFILENAME).pdb
	del $(MAKEFILENAME).ilk
	del $(MAKEFILENAME).exp
	del $(MAKEFILENAME).lib

**Comment by slacker-HD** [comment]
问题在于我的原始工程配置的是64位的，您这边想编译成32位程序，修改下重新配置就好。
